name: SSH Deploy to EC2 and Sync to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Run deployment on EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/AI-Sleep-Token-FE
          git pull origin main
          npm ci
          npm run build
          aws s3 sync ./dist s3://sleeptoken/ --delete
